# Generated by Django 5.1.7 on 2025-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_department_userprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('department_head', 'Chef de Département'), ('professor', 'Enseignant'), ('teacher', 'Enseignant'), ('student', 'Étudiant'), ('staff', 'Personnel Administratif'), ('scheduler', 'Planificateur')], default='student', max_length=20),
        ),
    ]
