# Generated by Django 5.1.7 on 2025-08-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('total_floors', models.IntegerField(default=1)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_capacity', models.IntegerField(default=30)),
                ('requires_special_equipment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(choices=[('RDC', 'Rez-de-chaussée'), ('1', '1er étage'), ('2', '2ème étage'), ('3', '3ème étage'), ('4', '4ème étage'), ('5', '5ème étage')], default='RDC', max_length=5)),
                ('capacity', models.IntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_blackboard', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=True)),
                ('has_audio_system', models.BooleanField(default=False)),
                ('is_laboratory', models.BooleanField(default=False)),
                ('laboratory_type', models.CharField(blank=True, max_length=50)),
                ('has_special_equipment', models.BooleanField(default=False)),
                ('equipment_list', models.JSONField(default=list)),
                ('is_accessible', models.BooleanField(default=True)),
                ('has_emergency_exit', models.BooleanField(default=True)),
                ('is_bookable', models.BooleanField(default=True)),
                ('priority_level', models.IntegerField(default=1)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['building__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('emergency', 'Urgence'), ('upgrade', 'Amélioration')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_scheduled', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('technician_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='rooms.room')),
            ],
            options={
                'ordering': ['-date_scheduled'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('meeting', 'Réunion'), ('conference', 'Conférence'), ('event', 'Événement'), ('maintenance', 'Maintenance'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('expected_attendees', models.IntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_working', models.BooleanField(default=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_equipment', to='rooms.room')),
            ],
            options={
                'ordering': ['room__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('period', models.CharField(choices=[('08:00-09:30', '08:00-09:30'), ('09:45-11:15', '09:45-11:15'), ('11:30-13:00', '11:30-13:00'), ('14:00-15:30', '14:00-15:30'), ('15:45-17:15', '15:45-17:15'), ('17:30-19:00', '17:30-19:00')], max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='rooms.room')),
            ],
            options={
                'ordering': ['room__code', 'day_of_week', 'period'],
                'unique_together': {('room', 'day_of_week', 'period')},
            },
        ),
    ]
