# Generated by Django 5.1.7 on 2025-10-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour les salles isolées (amphithéâtres, structures isolées, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building'),
        ),
    ]
