# Generated by Django 5.1.7 on 2025-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.IntegerField(default=0, help_text="Nombre d'étages (0 = seulement RDC)"),
        ),
    ]
