# Generated by Django 5.1.7 on 2025-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
