# Generated by Django 5.1.7 on 2025-10-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailability_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporaire'), ('recurring', 'Récurrente')], max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, help_text='Jour de la semaine', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_unavailabilities', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='courses.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher unavailabilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('time_slot', 'Créneau horaire préféré'), ('day', 'Jour préféré'), ('max_hours_per_day', 'Heures maximales par jour'), ('consecutive_days', 'Jours consécutifs'), ('break_time', 'Temps de pause'), ('room', 'Salle préférée'), ('avoid_time', 'Créneaux à éviter'), ('teaching_load', "Charge d'enseignement")], max_length=20)),
                ('priority', models.CharField(choices=[('required', 'Obligatoire'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', max_length=10)),
                ('preference_data', models.JSONField(default=dict, help_text='Données de préférence en format JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, help_text='Raison de la préférence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='courses.teacher')),
            ],
            options={
                'ordering': ['teacher', 'priority', 'preference_type'],
                'indexes': [models.Index(fields=['teacher', 'preference_type'], name='courses_tea_teacher_5e4f44_idx'), models.Index(fields=['priority', 'is_active'], name='courses_tea_priorit_878906_idx')],
            },
        ),
    ]
