# Generated by Django 5.1.7 on 2025-10-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_sessionfeedback_teacherschedulerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ml_complexity_level',
            field=models.CharField(blank=True, choices=[('Facile', 'Facile'), ('Moyenne', 'Moyenne'), ('Difficile', 'Difficile')], help_text='Niveau de complexité prédit par ML', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='ml_difficulty_score',
            field=models.FloatField(blank=True, help_text='Score de difficulté de planification ML (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ml_last_updated',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour des prédictions ML', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ml_prediction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées supplémentaires des prédictions ML'),
        ),
        migrations.AddField(
            model_name='course',
            name='ml_scheduling_priority',
            field=models.IntegerField(default=2, help_text='Priorité de planification ML: 1=haute, 2=moyenne, 3=basse'),
        ),
    ]
