# Generated by Django 5.1.7 on 2025-10-19 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_ml_complexity_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: INFO-L1-A', max_length=100)),
                ('code', models.CharField(help_text='Code unique de la classe', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('student_count', models.IntegerField(default=0, help_text="Nombre d'étudiants dans cette classe")),
                ('max_capacity', models.IntegerField(default=50, help_text='Capacité maximale de la classe')),
                ('academic_year', models.CharField(default='2024-2025', max_length=10)),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, help_text='Cursus/Programme de la classe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='courses.curriculum')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='courses.department')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('semester', models.CharField(default='S1', max_length=5)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('specific_student_count', models.IntegerField(blank=True, help_text="Nombre d'étudiants pour ce cours spécifiquement (sinon utilise l'effectif de la classe)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='courses.course')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='courses.studentclass')),
            ],
            options={
                'verbose_name': 'Cours de la classe',
                'verbose_name_plural': 'Cours des classes',
                'ordering': ['semester', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['code'], name='courses_stu_code_1f8e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['level', 'academic_year'], name='courses_stu_level_750714_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['department', 'is_active'], name='courses_stu_departm_6d2841_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classcourse',
            unique_together={('student_class', 'course')},
        ),
    ]
