# Generated by Django 5.1.7 on 2025-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentclass_classcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excluded_rooms',
            field=models.JSONField(default=list, help_text='IDs des salles à éviter'),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_rooms',
            field=models.JSONField(default=list, help_text='IDs des salles préférées'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_specific_room_type',
            field=models.CharField(blank=True, help_text='Type de salle requis (amphithéâtre, laboratoire, etc.)', max_length=50),
        ),
    ]
