# Generated by Django 5.1.7 on 2025-10-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_excluded_rooms_course_preferred_rooms_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='fixed_room',
            field=models.ForeignKey(blank=True, help_text='Salle fixe attribuée à cette classe (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_classes', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='fixed_schedule_pattern',
            field=models.JSONField(blank=True, default=dict, help_text="Modèle d'emploi du temps fixe: {jour: [{heure_debut, heure_fin, cours_id}]}"),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='has_fixed_schedule',
            field=models.BooleanField(default=False, help_text='Cette classe a-t-elle un emploi du temps fixe qui se répète chaque semaine?'),
        ),
    ]
