# Generated by Django 5.1.7 on 2025-10-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_studentclass_fixed_room_and_more'),
        ('rooms', '0003_alter_building_total_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='manual_scheduling_priority',
            field=models.IntegerField(choices=[(1, 'Très Haute (à planifier en premier)'), (2, 'Haute'), (3, 'Moyenne'), (4, 'Basse'), (5, 'Très Basse (flexible)')], default=3, help_text="Priorité de planification définie manuellement par l'admin"),
        ),
        migrations.AddField(
            model_name='course',
            name='use_manual_priority',
            field=models.BooleanField(default=False, help_text='Si True, utilise manual_scheduling_priority au lieu de ml_scheduling_priority'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('TPE', 'Travail Personnel Encadré'), ('CONF', 'Conférence'), ('EXAM', 'Examen')], default='CM', max_length=10),
        ),
        migrations.CreateModel(
            name='ClassRoomPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Obligatoire'), (2, 'Préférée'), (3, 'Acceptable')], default=2, help_text='Niveau de préférence pour cette salle')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette préférence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_preferences', to='rooms.room')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_preferences', to='courses.studentclass')),
            ],
            options={
                'verbose_name': 'Préférence de salle pour classe',
                'verbose_name_plural': 'Préférences de salles pour classes',
                'ordering': ['student_class', 'priority'],
                'unique_together': {('student_class', 'room')},
            },
        ),
    ]
