# Generated by Django 5.1.7 on 2025-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_studentclass_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=10),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=10),
        ),
    ]
