# Generated by Django 5.1.7 on 2025-08-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('rooms', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='conflict_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('curriculum', 'Par cursus'), ('teacher', 'Par enseignant'), ('room', 'Par salle'), ('global', 'Global')], default='curriculum', max_length=15),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('approved', 'Approuvé'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='schedule',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='utilization_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['academic_period', 'status'], name='schedules_s_academi_72d2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['curriculum', 'level'], name='schedules_s_curricu_0c2c87_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type', 'is_published'], name='schedules_s_schedul_68d17e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['schedule', 'time_slot'], name='schedules_s_schedul_40e04e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['teacher', 'time_slot'], name='schedules_s_teacher_2feb73_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['room', 'time_slot'], name='schedules_s_room_id_c208c0_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['course', 'session_type'], name='schedules_s_course__8f4c9e_idx'),
        ),
    ]
