# Generated by Django 5.1.7 on 2025-10-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_sessionfeedback_teacherschedulerequest'),
        ('rooms', '0001_initial'),
        ('schedules', '0002_schedule_approved_at_schedule_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bihebdomadaire'), ('monthly', 'Mensuel'), ('custom', 'Personnalisé')], default='weekly', max_length=15)),
                ('recurrence_pattern', models.CharField(blank=True, max_length=200)),
                ('flexibility_level', models.CharField(choices=[('rigid', 'Rigide'), ('balanced', 'Équilibré'), ('flexible', 'Flexible')], default='balanced', max_length=15)),
                ('allow_conflicts', models.BooleanField(default=False)),
                ('max_sessions_per_day', models.IntegerField(default=4)),
                ('respect_teacher_preferences', models.BooleanField(default=True)),
                ('respect_room_preferences', models.BooleanField(default=True)),
                ('optimization_priority', models.CharField(choices=[('teacher', 'Enseignant'), ('room', 'Salle'), ('balanced', 'Équilibré')], default='balanced', max_length=15)),
                ('excluded_dates', models.JSONField(default=list)),
                ('special_weeks', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_configs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_config', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Configuration de génération',
                'verbose_name_plural': 'Configurations de génération',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('rescheduled', 'Reprogrammé')], default='scheduled', max_length=15)),
                ('attendance_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_room_modified', models.BooleanField(default=False)),
                ('is_teacher_modified', models.BooleanField(default=False)),
                ('is_time_modified', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='schedules.sessionoccurrence')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('session_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='schedules.schedulesession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher')),
            ],
            options={
                'verbose_name': 'Occurrence de session',
                'verbose_name_plural': 'Occurrences de sessions',
                'ordering': ['actual_date', 'start_time'],
                'indexes': [models.Index(fields=['actual_date', 'status'], name='schedules_s_actual__145aaa_idx'), models.Index(fields=['room', 'actual_date'], name='schedules_s_room_id_45dc48_idx'), models.Index(fields=['teacher', 'actual_date'], name='schedules_s_teacher_314476_idx'), models.Index(fields=['session_template', 'actual_date'], name='schedules_s_session_70e8ed_idx')],
                'unique_together': {('session_template', 'actual_date', 'start_time')},
            },
        ),
    ]
