# Generated by Django 5.1.7 on 2025-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_sessionfeedback_teacherschedulerequest'),
        ('rooms', '0001_initial'),
        ('schedules', '0003_schedulegenerationconfig_sessionoccurrence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesession',
            unique_together={('schedule', 'time_slot', 'room', 'specific_date')},
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['specific_date'], name='schedules_s_specifi_056e86_idx'),
        ),
    ]
