# Generated by Django 5.1.7 on 2025-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_ml_complexity_level_and_more'),
        ('rooms', '0001_initial'),
        ('schedules', '0004_alter_schedulesession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesession',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='schedulesession',
            index=models.Index(fields=['schedule', 'time_slot', 'room'], name='schedules_s_schedul_500fe2_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulesession',
            constraint=models.UniqueConstraint(condition=models.Q(('specific_date__isnull', False)), fields=('schedule', 'time_slot', 'room', 'specific_date'), name='unique_schedule_session_with_date'),
        ),
    ]
