# Generated by Django 5.1.7 on 2025-10-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_schedulesession_unique_together_and_more'),
    ]

    operations = [
    ]
