# Generated by Django 5.1.7 on 2025-10-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentclass_classcourse_and_more'),
        ('schedules', '0006_auto_20251019_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedules_s_curricu_0c2c87_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.studentclass'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='courses.studentclass'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('class', 'Par classe'), ('teacher', 'Par enseignant'), ('room', 'Par salle'), ('global', 'Global')], default='class', max_length=15),
        ),
        migrations.AlterField(
            model_name='scheduleconstraint',
            name='constraint_type',
            field=models.CharField(choices=[('teacher_availability', 'Disponibilité enseignant'), ('room_availability', 'Disponibilité salle'), ('course_timing', 'Horaires de cours'), ('student_workload', 'Charge de travail étudiant'), ('resource_requirement', 'Exigence de ressource'), ('class_rule', 'Règle de classe'), ('custom', 'Personnalisée')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['student_class', 'level'], name='schedules_s_student_85aad3_idx'),
        ),
    ]
