# Generated by Django 5.1.7 on 2025-10-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_schedule_schedules_s_curricu_0c2c87_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='avoid_single_sessions',
            field=models.BooleanField(default=True, help_text='Éviter les journées avec une seule session'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='distribute_evenly',
            field=models.BooleanField(default=True, help_text='Distribuer équitablement les cours sur la semaine'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='excluded_days',
            field=models.JSONField(default=list, help_text="Jours exclus ['saturday', 'sunday']"),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='group_same_subject',
            field=models.BooleanField(default=False, help_text="Grouper les sessions d'une même matière"),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='max_consecutive_sessions',
            field=models.IntegerField(default=3, help_text='Nombre max de sessions consécutives'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='max_hours_per_day_students',
            field=models.IntegerField(default=8, help_text='Heures max par jour pour les étudiants'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='max_hours_per_day_teachers',
            field=models.IntegerField(default=6, help_text='Heures max par jour pour un enseignant'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='max_hours_per_week_students',
            field=models.IntegerField(default=30, help_text='Heures max par semaine pour les étudiants'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='min_break_between_sessions',
            field=models.IntegerField(default=15, help_text='Minutes de pause minimale entre sessions'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='min_rest_time_teachers',
            field=models.IntegerField(default=30, help_text='Temps de repos min entre cours (minutes)'),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='preferred_days',
            field=models.JSONField(default=list, help_text="Jours préférés ['monday', 'tuesday', etc.]"),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='preferred_end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin préférée (ex: 18:00)', null=True),
        ),
        migrations.AddField(
            model_name='schedulegenerationconfig',
            name='preferred_start_time',
            field=models.TimeField(blank=True, help_text='Heure de début préférée (ex: 08:00)', null=True),
        ),
    ]
