# Generated by Django 5.1.7 on 2025-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_schedulegenerationconfig_avoid_single_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=5),
        ),
    ]
